### ISSUE TITLE
`Items` data models

### ISSUE THREAD

**Issue by kostysh** [windingtree/stays-models#11]
Should be implemented `payload` data models for `Items` of `Space` (as `OtherItems`)
At the moment should be implemented models for the following items:

- [ ] Breakfast
- [ ] Parking near the hotel
- [ ] Early check-in
- [ ] Late check-in

Each item must be defined with:

- Unique Id
- Name
- Description
- Photos
